version: '3.5'

services:
  postgres_comments:
    container_name: postgres_comments_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres_comments:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - postgres_comments
    restart: unless-stopped

  comments_service:
    container_name: comments_service_container
    build:
      context: ../back-end
    environment:
      POSTGRES_URL: postgres://postgres:123456@postgres_comments:5432/postgres_db
      MONGODB_URL: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: somesecret
      JWT_TTL: 1d
      IS_PROD: false
      AWS_ACCESS_KEY_ID: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_REGION: 
      AWS_S3_BUCKET_NAME: 
      AWS_BASE_URL: 
      RABBIT_URL: amqp://rabbitmq:5672
      RABBIT_QUEUE: main_queue
    depends_on:
      - postgres_comments
      - redis
      - rabbitmq
    ports:
      - "3000:3000"
      - "8080:8080"
    networks:
      - postgres_comments
      - redis
      - rabbitmq
      - client-server
    restart: unless-stopped

  comments_client:
    container_name: comments_client_container
    build:
      context: ../front-end
    environment:
      BASE_URL: http://comments_service:3000
      BASE_WS: comments_service:8080
    ports:
      - "3001:3001"
    networks:
      - client-server
    depends_on:
      - comments_service
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq
    restart: unless-stopped

networks:
  postgres_comments:
    driver: bridge
  redis:
    driver: bridge
  rabbitmq:
    driver: bridge
  client-server:
    driver: bridge

volumes:
    postgres_comments: