version: '3.5'

services:
  postgres_comments:
    container_name: postgres_comments_container
    build: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres_comments:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - postgres_comments
    restart: unless-stopped

  comments_service:
    container_name: comments_service_container
    build: ..
    environment:
      DB_HOST: postgres_post
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      DB_NAME: ${POSTGRES_DB:-postgres_db}
    depends_on:
      - postgres_comments
    ports:
      - "3000:3000"
    networks:
      - postgres_comments
    restart: unless-stopped

networks:
    postgres_comments:
      driver: bridge

volumes:
    postgres_comments: